name: Deploy Site
on:
    push:
        branches: 
            - main
jobs:
    update-s3:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Upload page
              uses: jakejarvis/s3-sync-action@master
              env:
                AWS_S3_BUCKET: ci-cd-laboratory
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
